// <auto-generated />
using System;
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Data.Migrations
{
    [DbContext(typeof(GarageAppDbContext))]
    partial class GarageAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.DbModels.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TypeCar")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GarageId = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            TypeCar = 1,
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            GarageId = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            IsAvailable = false,
                            Make = "Honda",
                            Model = "Civic",
                            TypeCar = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            GarageId = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Focus",
                            TypeCar = 2,
                            Year = 2016
                        },
                        new
                        {
                            Id = 4,
                            GarageId = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X5",
                            TypeCar = 3,
                            Year = 2021
                        },
                        new
                        {
                            Id = 5,
                            GarageId = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            IsAvailable = false,
                            Make = "Audi",
                            Model = "A4",
                            TypeCar = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            GarageId = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            IsAvailable = true,
                            Make = "Volkswagen",
                            Model = "Golf",
                            TypeCar = 2,
                            Year = 2017
                        },
                        new
                        {
                            Id = 7,
                            GarageId = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            IsAvailable = true,
                            Make = "Mercedes",
                            Model = "C-Class",
                            TypeCar = 1,
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            GarageId = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            IsAvailable = false,
                            Make = "Nissan",
                            Model = "Leaf",
                            TypeCar = 99,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            GarageId = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "3",
                            TypeCar = 2,
                            Year = 2015
                        },
                        new
                        {
                            Id = 10,
                            GarageId = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            IsAvailable = true,
                            Make = "Jeep",
                            Model = "Wrangler",
                            TypeCar = 18,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("GarageApp.DbModels.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd048be6-8b26-4e87-be6a-52eea8410577"),
                            Location = "Main Street 1",
                            Name = "Central Garage"
                        },
                        new
                        {
                            Id = new Guid("6eb61664-d5f8-4030-9a8a-b41a1553b975"),
                            Location = "West Avenue 24",
                            Name = "Westside Garage"
                        },
                        new
                        {
                            Id = new Guid("e24b1d1d-8eea-4030-a740-d508e2d93252"),
                            Location = "Airport Road 7",
                            Name = "Airport Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.DbModels.Car", b =>
                {
                    b.HasOne("GarageApp.DbModels.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.DbModels.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
